[package]
name = "rialo-agent-marketplace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rialo-venus-proc-macro = "*"
rialo-venus = "*"
rialo-subscriber-interface = "*"
rialo-s-program = "*"
rialo-s-program-error = "*"
rialo-rex-processor-interface = "*"
rialo-types = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
